server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
    
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///d:/config-repo
  profiles:
    active: native
    