server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/stanislav-zhurich/configuration-repo
          searchPaths: catalog-service
          username: stanislav-zhurich
          password: 080587Stas103   
    